version: 2

jobs:
  build:
    environment:
      IMAGE_NAME: otherguy/dropbox
      GITHUB_PACKAGE: docker.pkg.github.com/otherguy/docker-dropbox/dropbox
      IMAGE_TAG: latest
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build --build-arg BUILD_DATE="$(date --rfc-3339=seconds | sed 's/ /T/')" --build-arg VCS_REF="$(echo $CIRCLE_SHA1 | cut -c -7)" --tag "${IMAGE_NAME}:${IMAGE_TAG}" .
      - run:
          name: Publish latest to Docker Hub
          command: |
            echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
            docker push ${IMAGE_NAME}:${IMAGE_TAG}
      - run:
          name: Publish latest to GitHub
          command: |
            echo "${GITHUB_TOKEN}" | docker login docker.pkg.github.com -u "${GITHUB_USERNAME}" --password-stdin
            docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${GITHUB_PACKAGE}:${IMAGE_TAG}
            docker push ${GITHUB_PACKAGE}:${IMAGE_TAG}
      - run:
          name: Publish tag to Docker Hub
          command: |
            if [ -n "${CIRCLE_TAG}" ]
            then
              docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:${CIRCLE_TAG}
              docker push ${IMAGE_NAME}:${CIRCLE_TAG}
            fi
      - run:
          name: Publish tag to GitHub
          command: |
            if [ -n "${CIRCLE_TAG}" ]
            then
              docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${GITHUB_PACKAGE}:${CIRCLE_TAG}
              docker push ${GITHUB_PACKAGE}:${CIRCLE_TAG}
            fi

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
  build-tags:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
