version: 2

jobs:
  build:
    environment:
      IMAGE_NAME: otherguy/docker
      IMAGE_TAG: latest
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build --build-arg BUILD_DATE=$(date --rfc-3339=seconds | sed 's/ /T/') --build-arg VCS_REF=$(echo $CIRCLE_SHA1 | cut -c -7) --tag $IMAGE_NAME:$IMAGE_TAG .
      - run:
          name: Publish latest to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
      - run:
          name: Publish tag to Docker Hub
          command: |
            if [ -n "$CIRCLE_TAG" ]
            then
              docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_TAG
              docker push $IMAGE_NAME:$CIRCLE_TAG
            fi

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
  build-tags:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/